In [37]:
import numpy as np

In [38]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [39]:
array.min(), array.max()

(10, 500)

In [40]:
array.sum()

1338

In [41]:
array.mean()

111.5

In [42]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.min(), array.argmin()

(10, 3)

In [43]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.max(), array.argmax()

(500, 2)

In [44]:
array[array>100]

array([500, 310, 101, 203])

In [45]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])

In [46]:
array[-1]


30

In [47]:
array[-2:]

array([203,  30])

In [48]:
array[array % 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [49]:
array[(array % 2 == 0) & (array > 50)] 

array([500, 310])

In [50]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])


In [52]:
array[(array % 3 == 0)|(array < 40)]

array([23, 10, 30, 20, 30, 30])